// flow-typed signature: c643c278043e7611f2dd26baa50a2e6f
// flow-typed version: <<STUB>>/react-native_v>=0.40.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native' {
  declare module.exports: any;
}
